version: '3'

services:
  dbserver:
    image: mariadb:5.5.57
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ichijou1234
    env_file:
      - ./environments/db.env
    ports:
      - 3306:3306
    volumes:
      - mysqlvolume:/var/lib/mysql

  mongoserver:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongovolume:/data/db

  fileserver:
    image: cb/fileserver
    restart: always
    volumes:
      - filestoragevol:/home/node/app/static

  webserver:
    image: cb/webserver
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - authapi
      - livechatapi
      - socketserver
    volumes:
      - filestoragevol:/filestorage

  authapi:
    image: cb/authapi
    restart: always
    env_file:
      - ./environments/node.env
      - ./environments/db.env
      - ./environments/email.env
    depends_on:
      - dbserver

  userapi:
    image: cb/userapi
    restart: always
    env_file:
      - ./environments/node.env
      - ./environments/db.env
    depends_on:
      - dbserver

  livechatapi:
    image: cb/livechatapi
    restart: always
    env_file:
      - ./environments/node.env
      - ./environments/db.env
    depends_on:
      - dbserver

  socketserver:
    image: cb/socketserver
    restart: always
    env_file:
      - ./environments/node.env
      - ./environments/db.env
    depends_on:
      - dbserver

  chatbotapi:
    image: cb/chatbotapi
    restart: always
    env_file:
      - ./environments/node.env
      - ./environments/db.env
    depends_on:
      - dbserver
      - mongoserver
    volumes:
      - tmpcbvolume:/cb_datas

  cbengine:
    image: cb/cbengine
    restart: always
    ports:
      - 5000:5000
    volumes:
      - tmpcbvolume:/cb_datas

volumes:
  mongovolume:
  mysqlvolume:
  filestoragevol:
  tmpcbvolume: