version: '3'

services:
  dbserver:
    image: cb/dbserver
    build: ./dbserver
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ichijou1234
    env_file:
        - ./environments/db.env
    ports:
        - 3306:3306
    volumes:
        - ./dbserver/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  webserver:
    image: cb/webserver
    build: ./webserver
    restart: always
    ports:
        - 80:80
        - 443:443
    depends_on:
        - authapi
        - livechatapi
        - socketserver

  authapi:
    image: cb/authapi
    build: ./authapi
    restart: always
    env_file:
        - ./environments/node.env
        - ./environments/db.env
        - ./environments/email.env
    depends_on:
        - dbserver
    volumes:
        - ./authapi/src:/home/node/app/src

  userapi:
    image: cb/userapi
    build: ./userapi
    restart: always
    env_file:
        - ./environments/node.env
        - ./environments/db.env
    depends_on:
        - dbserver
    volumes:
        - ./userapi/src:/home/node/app/src

  livechatapi:
    image: cb/livechatapi
    build: ./livechatapi
    restart: always
    env_file:
        - ./environments/node.env
        - ./environments/db.env
    depends_on:
        - dbserver
    volumes:
        - ./livechatapi/src:/home/node/app/src

  socketserver:
    image: cb/socketserver
    build: ./socketserver
    restart: always
    env_file:
        - ./environments/node.env
        - ./environments/db.env
    depends_on:
        - dbserver
    volumes:
        - ./socketserver/src:/home/node/app/src

  chatbotapi:
    image: cb/chatbotapi
    build: ./chatbotapi
    restart: always
    env_file:
        - ./environments/node.env
        - ./environments/db.env
    depends_on:
        - dbserver
    volumes:
        - ./chatbotapi/src:/home/node/app/src

  nluserver:
    image: rasa/rasa_nlu
    restart: always
    ports:
      - 5000:5000
    volumes:
      - botproject:/app/projects

  coreserver:
    image: cb/coreserver
    build: ./coreserver
    restart: always
    ports:
      - 5001:80
    volumes:
      - botproject:/app/projects
      - ./coreserver/src:/usr/src

  chatbotengine:
    image: cb/chatbotengine
    build: ./chatbotengine
    restart: always
    ports:
      - 5002:80
    volumes:
      - botproject:/app/projects
      - ./chatbotengine/src:/usr/src

volumes:
  botproject: