version: '3'

services:
    dbserver:
        image: cb/dbserver
        build: ./dbserver
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ichijou1234
        env_file:
            - ./environments/db.env
        ports:
            - 3306:3306
        volumes:
            - ./dbserver/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    webserver:
        image: cb/webserver
        build: ./webserver
        restart: always
        ports:
            - 80:80
            - 443:443
        depends_on:
            - authapi
            - socketlivechat

    authapi:
        image: cb/authapi
        build: ./authapi
        restart: always
        env_file:
            - ./environments/node.env
            - ./environments/db.env
            - ./environments/email.env
        depends_on:
            - dbserver
        volumes:
            - ./authapi/src:/home/node/app/src

    livechatapi:
        image: cb/livechatapi
        build: ./livechatapi
        restart: always
        env_file:
            - ./environments/node.env
            - ./environments/db.env
        depends_on:
            - dbserver
        volumes:
            - ./livechatapi/src:/home/node/app/src

    socketlivechat:
        image: cb/socketlivechat
        build: ./socketlivechat
        restart: always
        env_file:
            - ./environments/node.env
            - ./environments/db.env
        depends_on:
            - dbserver
        volumes:
            - ./socketlivechat/src:/home/node/app/src